# Generated by Django 3.2.9 on 2021-12-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('course_no', models.CharField(db_column='Course_no', max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, db_column='Course_Name', max_length=50, null=True)),
                ('time_slot', models.TimeField(blank=True, db_column='Time_slot', null=True)),
                ('exam_date', models.DateField(blank=True, db_column='Exam_date', null=True)),
            ],
            options={
                'db_table': 'exam',
                'managed': False,
            },
        ),
    ]
