# Generated by Django 3.2.9 on 2021-12-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.CharField(db_column='Room_no', max_length=20, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True)),
                ('avaliability_status', models.CharField(blank=True, db_column='Avaliability_status', max_length=25, null=True)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
    ]
