# Generated by Django 3.2.9 on 2021-12-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='temp_room',
        ),
    ]
