# Generated by Django 3.2.9 on 2021-12-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
