# Generated by Django 3.2.9 on 2021-12-22 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invigilator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_date', models.DateField()),
                ('free_time', models.TimeField()),
                ('invigilator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='invigilator.invigilator')),
            ],
            options={
                'db_table': 'timetable',
            },
        ),
    ]
