# Generated by Django 3.2.9 on 2021-12-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='invigilator_id',
            new_name='invigilator',
        ),
    ]
