# Generated by Django 3.2.9 on 2021-12-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_rename_invigilator_id_timetable_invigilator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'managed': False},
        ),
    ]
