# Generated by Django 3.2.9 on 2021-12-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='schedule')),
            ],
        ),
    ]
